level: 4
horizon: 15
num_nodes: 10
edges:
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 2
  - 4
- - 1
  - 4
- - 2
  - 5
- - 2
  - 6
- - 3
  - 7
- - 5
  - 8
- - 7
  - 8
- - 7
  - 9
- - 4
  - 8
- - 6
  - 9
- - 7
  - 8
- &id001
  - 5
  - 8
- *id001
supply_nodes:
- 0
demand_nodes:
- 8
- 9
demand_sinusoidal:
- node: 8
  base: 7.5
  amplitude: 1.9
  phase: 0.41
- node: 9
  base: 9.7
  amplitude: 1.5
  phase: 1.71
availability:
  open_probability: 0.83
  per_edge:
  - 0.88
  - 0.88
  - 0.73
  - 0.78
  - 0.8
  - 0.8
  - 0.87
  - 0.9
  - 0.74
  - 0.82
  - 0.84
  - 0.75
  - 0.7
  - 0.8
  - 0.87
  - 0.76
risk:
  per_edge_range:
  - - 0.032
    - 0.149
  - - 0.03
    - 0.108
  - - 0.032
    - 0.115
  - - 0.027
    - 0.127
  - - 0.063
    - 0.156
  - - 0.019
    - 0.082
  - - 0.038
    - 0.085
  - - 0.04
    - 0.107
  - - 0.036
    - 0.121
  - - 0.051
    - 0.144
  - - 0.012
    - 0.068
  - - 0.018
    - 0.09
  - - 0.011
    - 0.082
  - - 0.073
    - 0.156
  - - 0.042
    - 0.144
  - - 0.063
    - 0.147
loss_penalty: 1.55
edge_capacity:
- 19.8
- 11.8
- 11.5
- 15.4
- 13.3
- 12.4
- 10.3
- 17.7
- 11.0
- 19.4
- 11.2
- 13.0
- 15.2
- 13.0
- 10.2
- 12.6
edge_cost:
- 1.23
- 1.14
- 1.34
- 1.35
- 1.2
- 1.15
- 1.1
- 1.24
- 1.33
- 0.91
- 0.96
- 1.1
- 1.11
- 0.91
- 1.11
- 1.12
initial_inventory:
- 91.0
- 6.5
- 6.9
- 0.7
- 4.9
- 2.0
- 5.3
- 0.8
- 7.2
- 1.2
supply_injection:
  per_period:
  - node: 0
    amount: 9.36
weights:
  supply_reward_weight: 1.0
  cost_weight: 0.095
  risk_weight: 0.309
cvar:
  lambda: 0.0
  tau: 0.2
