level: 3
horizon: 14
num_nodes: 12
edges:
- - 0
  - 1
- &id001
  - 0
  - 2
- - 0
  - 3
- - 1
  - 4
- - 2
  - 4
- - 2
  - 5
- - 1
  - 6
- &id002
  - 2
  - 6
- - 1
  - 7
- - 3
  - 7
- &id003
  - 4
  - 8
- - 7
  - 9
- - 5
  - 10
- - 4
  - 10
- - 6
  - 11
- - 0
  - 8
- - 3
  - 10
- - 5
  - 11
- *id001
- *id002
- *id003
- - 9
  - 8
supply_nodes:
- 0
demand_nodes:
- 8
- 9
- 10
- 11
demand_waves:
- node: 8
  base: 8.8
  amplitude: 2.21
  freq: 0.59
  phase: 0.75
  func: cos
- node: 9
  base: 10.1
  amplitude: 2.5
  freq: 0.68
  phase: 1.19
  func: sin
- node: 10
  base: 9.5
  amplitude: 0.59
  freq: 0.86
  phase: 0.54
  func: cos
- node: 11
  base: 10.2
  amplitude: 4.01
  freq: 0.52
  phase: 0.96
  func: sin
noise_std: 1.18
edge_capacity:
- 26.0
- 25.6
- 20.9
- 17.8
- 16.5
- 14.7
- 23.9
- 16.9
- 21.1
- 25.7
- 16.1
- 19.1
- 15.6
- 25.1
- 18.7
- 16.8
- 16.8
- 24.8
- 26.1
- 18.3
- 24.7
- 24.0
edge_cost:
- 1.17
- 1.11
- 1.18
- 1.08
- 1.04
- 1.24
- 1.15
- 1.13
- 0.95
- 1.12
- 1.06
- 1.12
- 0.96
- 1.1
- 0.93
- 5.25
- 1.82
- 1.06
- 0.99
- 1.09
- 1.12
- 0.97
availability_default: true
risk_default: 0.0
loss_penalty: 1.37
initial_inventory:
- 116.3
- 1.4
- 3.2
- 3.2
- 2.3
- 11.2
- 9.9
- 3.2
- 7.2
- 8.5
- 13.6
- 5.0
supply_injection:
  per_period:
  - node: 0
    amount: 9.07
weights:
  supply_reward_weight: 1.0
  cost_weight: 0.068
  risk_weight: 0.021
cvar:
  lambda: 0.0
  tau: 0.2
