level: 3
horizon: 19
num_nodes: 16
edges:
- - 0
  - 1
- &id001
  - 0
  - 2
- - 0
  - 3
- &id002
  - 0
  - 4
- - 2
  - 5
- - 1
  - 6
- &id003
  - 4
  - 7
- - 2
  - 7
- - 3
  - 6
- - 7
  - 8
- - 6
  - 8
- - 5
  - 9
- - 6
  - 10
- - 6
  - 11
- - 10
  - 12
- - 9
  - 13
- - 8
  - 13
- - 9
  - 14
- - 8
  - 15
- - 11
  - 15
- - 0
  - 15
- - 1
  - 11
- - 2
  - 13
- - 5
  - 9
- - 6
  - 8
- *id001
- *id002
- *id003
- - 15
  - 13
supply_nodes:
- 0
demand_nodes:
- 12
- 13
- 14
- 15
demand_waves:
- node: 12
  base: 12.0
  amplitude: 1.93
  freq: 0.84
  phase: 1.5
  func: cos
- node: 13
  base: 9.1
  amplitude: 1.92
  freq: 0.37
  phase: 2.14
  func: cos
- node: 14
  base: 7.7
  amplitude: 2.76
  freq: 0.33
  phase: 1.35
  func: cos
- node: 15
  base: 10.0
  amplitude: 4.4
  freq: 0.31
  phase: 2.94
  func: cos
noise_std: 2.01
edge_capacity:
- 21.1
- 24.0
- 18.3
- 25.7
- 17.8
- 17.9
- 15.0
- 15.2
- 14.4
- 19.9
- 16.6
- 19.2
- 19.6
- 16.6
- 25.3
- 19.2
- 20.2
- 16.9
- 19.6
- 16.0
- 18.5
- 19.0
- 15.2
- 20.9
- 22.6
- 22.5
- 25.2
- 15.8
- 26.2
edge_cost:
- 0.97
- 0.95
- 1.06
- 0.93
- 1.1
- 1.16
- 1.14
- 1.04
- 1.03
- 1.23
- 1.0
- 0.96
- 0.93
- 1.09
- 1.13
- 1.17
- 0.99
- 1.09
- 1.16
- 1.01
- 6.7
- 1.43
- 2.97
- 0.98
- 0.99
- 0.91
- 1.14
- 0.94
- 1.12
availability_default: true
risk_default: 0.0
loss_penalty: 1.4
initial_inventory:
- 121.8
- 0.9
- 10.0
- 2.0
- 13.8
- 7.3
- 13.3
- 13.5
- 7.4
- 9.2
- 1.1
- 4.5
- 2.5
- 3.6
- 0.1
- 7.0
supply_injection:
  per_period:
  - node: 0
    amount: 8.51
weights:
  supply_reward_weight: 1.0
  cost_weight: 0.109
  risk_weight: 0.039
cvar:
  lambda: 0.0
  tau: 0.2
