level: 3
horizon: 18
num_nodes: 15
edges:
- - 0
  - 1
- &id001
  - 0
  - 2
- - 0
  - 3
- &id002
  - 1
  - 4
- - 2
  - 4
- - 3
  - 5
- - 2
  - 5
- - 3
  - 6
- - 1
  - 6
- &id003
  - 2
  - 7
- - 6
  - 8
- - 4
  - 9
- - 7
  - 9
- - 4
  - 10
- - 6
  - 10
- &id004
  - 5
  - 8
- - 8
  - 11
- - 10
  - 12
- - 9
  - 12
- - 9
  - 13
- - 10
  - 14
- &id005
  - 0
  - 11
- - 4
  - 12
- - 1
  - 12
- &id006
  - 5
  - 8
- *id001
- *id002
- *id003
- *id004
- *id005
- *id006
- - 14
  - 13
supply_nodes:
- 0
demand_nodes:
- 11
- 12
- 13
- 14
demand_waves:
- node: 11
  base: 7.2
  amplitude: 0.96
  freq: 0.57
  phase: 1.86
  func: cos
- node: 12
  base: 11.7
  amplitude: 2.28
  freq: 0.35
  phase: 3.01
  func: cos
- node: 13
  base: 8.8
  amplitude: 1.74
  freq: 0.55
  phase: 3.09
  func: sin
- node: 14
  base: 11.0
  amplitude: 2.32
  freq: 0.48
  phase: 2.79
  func: sin
noise_std: 1.62
edge_capacity:
- 26.2
- 14.8
- 19.0
- 21.8
- 17.3
- 19.7
- 19.2
- 17.2
- 24.8
- 16.1
- 21.1
- 19.5
- 15.2
- 18.2
- 25.6
- 21.5
- 18.5
- 22.4
- 19.7
- 17.1
- 26.4
- 25.0
- 25.6
- 23.9
- 23.3
- 17.9
- 19.8
- 22.3
- 18.5
- 25.5
- 20.3
- 25.5
edge_cost:
- 1.02
- 0.92
- 1.1
- 1.16
- 1.16
- 1.08
- 1.11
- 1.06
- 1.06
- 1.04
- 1.21
- 0.92
- 1.21
- 1.02
- 1.17
- 0.93
- 1.25
- 1.16
- 1.03
- 1.11
- 1.2
- 6.23
- 1.9
- 4.03
- 1.01
- 1.23
- 1.18
- 1.24
- 0.93
- 7.36
- 1.09
- 1.17
availability_default: true
risk_default: 0.0
loss_penalty: 1.57
initial_inventory:
- 84.9
- 8.5
- 12.5
- 1.6
- 2.3
- 9.4
- 9.7
- 4.1
- 2.1
- 10.9
- 13.9
- 7.2
- 12.6
- 5.7
- 7.0
supply_injection:
  per_period:
  - node: 0
    amount: 7.54
weights:
  supply_reward_weight: 1.0
  cost_weight: 0.094
  risk_weight: 0.045
cvar:
  lambda: 0.0
  tau: 0.2
