level: 3
horizon: 18
num_nodes: 15
edges:
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 2
  - 4
- - 3
  - 4
- - 2
  - 5
- - 3
  - 5
- - 3
  - 6
- - 1
  - 6
- &id001
  - 3
  - 7
- - 4
  - 8
- &id002
  - 5
  - 8
- - 5
  - 9
- - 4
  - 10
- - 4
  - 11
- - 5
  - 11
- - 6
  - 8
- - 7
  - 8
- - 11
  - 12
- - 9
  - 12
- - 8
  - 13
- - 9
  - 14
- &id003
  - 10
  - 14
- - 2
  - 8
- *id001
- *id002
- *id003
- - 12
  - 13
supply_nodes:
- 0
demand_nodes:
- 12
- 13
- 14
demand_waves:
- node: 12
  base: 10.1
  amplitude: 0.54
  freq: 0.49
  phase: 2.61
  func: cos
- node: 13
  base: 8.6
  amplitude: 1.63
  freq: 0.61
  phase: 0.24
  func: cos
- node: 14
  base: 7.3
  amplitude: 1.64
  freq: 0.37
  phase: 0.22
  func: cos
noise_std: 2.13
edge_capacity:
- 25.1
- 19.7
- 23.8
- 22.5
- 26.4
- 16.6
- 16.6
- 21.6
- 22.2
- 16.6
- 18.4
- 18.2
- 20.2
- 26.3
- 17.7
- 15.0
- 16.9
- 18.4
- 25.7
- 16.4
- 24.0
- 18.3
- 23.7
- 17.0
- 16.4
- 16.6
- 20.1
- 21.3
edge_cost:
- 1.02
- 0.94
- 1.01
- 1.04
- 0.92
- 1.23
- 1.02
- 0.98
- 1.18
- 1.0
- 1.1
- 0.94
- 1.1
- 1.22
- 1.18
- 1.02
- 1.02
- 0.94
- 1.16
- 1.03
- 0.97
- 1.04
- 1.09
- 1.76
- 0.92
- 1.05
- 0.96
- 1.05
availability_default: true
risk_default: 0.0
loss_penalty: 1.58
initial_inventory:
- 117.2
- 8.2
- 8.7
- 2.7
- 3.5
- 8.5
- 4.1
- 9.7
- 13.7
- 2.1
- 1.0
- 1.0
- 7.5
- 12.3
- 2.2
supply_injection:
  per_period:
  - node: 0
    amount: 10.75
weights:
  supply_reward_weight: 1.0
  cost_weight: 0.088
  risk_weight: 0.003
cvar:
  lambda: 0.0
  tau: 0.2
