level: 3
horizon: 11
num_nodes: 12
edges:
- - 0
  - 1
- - 0
  - 2
- &id001
  - 0
  - 3
- &id002
  - 0
  - 4
- - 2
  - 5
- - 1
  - 6
- - 1
  - 7
- - 3
  - 8
- - 4
  - 5
- - 7
  - 9
- - 7
  - 10
- &id003
  - 8
  - 10
- - 7
  - 11
- &id004
  - 5
  - 11
- &id005
  - 6
  - 10
- - 8
  - 9
- - 6
  - 10
- - 4
  - 8
- *id001
- *id002
- *id003
- *id004
- *id005
- - 9
  - 10
supply_nodes:
- 0
demand_nodes:
- 9
- 10
- 11
demand_waves:
- node: 9
  base: 11.1
  amplitude: 2.46
  freq: 0.5
  phase: 0.38
  func: sin
- node: 10
  base: 8.3
  amplitude: 0.12
  freq: 0.66
  phase: 0.99
  func: sin
- node: 11
  base: 7.0
  amplitude: 1.0
  freq: 0.4
  phase: 2.67
  func: cos
noise_std: 2.02
edge_capacity:
- 19.0
- 15.4
- 23.0
- 21.5
- 14.5
- 22.0
- 18.3
- 16.8
- 24.3
- 15.5
- 23.6
- 21.1
- 21.0
- 24.8
- 24.8
- 24.0
- 21.2
- 21.3
- 24.2
- 24.3
- 23.0
- 20.3
- 17.3
- 26.4
edge_cost:
- 1.02
- 0.98
- 0.98
- 0.99
- 1.07
- 1.04
- 1.08
- 1.13
- 0.91
- 1.24
- 0.97
- 1.03
- 0.98
- 1.18
- 0.96
- 0.92
- 1.02
- 1.24
- 1.18
- 1.09
- 1.24
- 1.06
- 1.15
- 0.99
availability_default: true
risk_default: 0.0
loss_penalty: 1.53
initial_inventory:
- 104.2
- 10.6
- 4.6
- 0.7
- 11.8
- 7.7
- 7.3
- 10.6
- 7.9
- 4.8
- 4.4
- 0.8
supply_injection:
  per_period:
  - node: 0
    amount: 5.79
weights:
  supply_reward_weight: 1.0
  cost_weight: 0.057
  risk_weight: 0.045
cvar:
  lambda: 0.0
  tau: 0.2
