level: 3
horizon: 10
num_nodes: 11
edges:
- - 0
  - 1
- - 0
  - 2
- - 2
  - 3
- - 1
  - 3
- &id001
  - 2
  - 4
- - 1
  - 4
- &id002
  - 2
  - 5
- - 1
  - 5
- &id003
  - 5
  - 6
- - 5
  - 7
- - 4
  - 7
- - 3
  - 6
- - 6
  - 8
- - 6
  - 9
- - 6
  - 10
- - 7
  - 10
- - 6
  - 10
- *id001
- *id002
- *id003
- - 9
  - 8
supply_nodes:
- 0
demand_nodes:
- 8
- 9
- 10
demand_waves:
- node: 8
  base: 7.7
  amplitude: 3.39
  freq: 0.9
  phase: 1.1
  func: sin
- node: 9
  base: 11.0
  amplitude: 1.0
  freq: 0.43
  phase: 2.64
  func: cos
- node: 10
  base: 10.5
  amplitude: 3.77
  freq: 0.72
  phase: 1.95
  func: cos
noise_std: 1.79
edge_capacity:
- 17.1
- 16.1
- 21.9
- 15.0
- 17.1
- 18.4
- 17.0
- 12.7
- 20.9
- 16.5
- 19.9
- 18.7
- 22.0
- 13.8
- 13.8
- 18.0
- 18.5
- 13.8
- 15.3
- 15.2
- 16.8
edge_cost:
- 1.12
- 0.98
- 1.23
- 1.05
- 0.93
- 0.92
- 0.94
- 1.2
- 1.02
- 0.94
- 1.01
- 1.04
- 0.92
- 1.23
- 1.02
- 0.98
- 1.18
- 1.0
- 1.1
- 0.94
- 1.21
availability_default: true
risk_default: 0.0
loss_penalty: 1.12
initial_inventory:
- 107.1
- 3.3
- 9.6
- 0.6
- 4.1
- 2.5
- 4.1
- 4.0
- 1.3
- 11.3
- 9.0
supply_injection:
  per_period:
  - node: 0
    amount: 7.24
weights:
  supply_reward_weight: 1.0
  cost_weight: 0.106
  risk_weight: 0.015
cvar:
  lambda: 0.0
  tau: 0.2
