level: 3
horizon: 13
num_nodes: 12
edges:
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 2
  - 4
- - 2
  - 5
- - 2
  - 6
- - 1
  - 4
- - 3
  - 5
- - 6
  - 7
- &id001
  - 5
  - 7
- - 4
  - 8
- &id002
  - 5
  - 8
- &id003
  - 4
  - 9
- - 5
  - 9
- - 7
  - 10
- - 9
  - 10
- - 7
  - 11
- - 8
  - 10
- &id004
  - 2
  - 10
- - 4
  - 7
- *id001
- *id002
- *id003
- *id004
- - 11
  - 10
supply_nodes:
- 0
demand_nodes:
- 10
- 11
demand_waves:
- node: 10
  base: 9.2
  amplitude: 2.52
  freq: 0.53
  phase: 0.77
  func: sin
- node: 11
  base: 11.5
  amplitude: 3.59
  freq: 0.58
  phase: 0.89
  func: cos
noise_std: 0.91
edge_capacity:
- 18.5
- 13.9
- 12.2
- 20.9
- 18.7
- 12.4
- 19.4
- 16.8
- 16.7
- 19.7
- 15.7
- 19.0
- 16.2
- 14.4
- 15.8
- 14.0
- 13.7
- 18.6
- 17.0
- 17.8
- 15.7
- 16.6
- 13.2
- 21.0
- 13.9
edge_cost:
- 1.13
- 0.93
- 1.2
- 1.24
- 1.09
- 1.13
- 1.15
- 1.08
- 1.24
- 1.12
- 1.09
- 1.17
- 1.01
- 1.01
- 1.11
- 0.95
- 1.24
- 1.02
- 4.63
- 1.17
- 1.11
- 0.94
- 1.01
- 5.3
- 1.03
availability_default: true
risk_default: 0.0
loss_penalty: 1.16
initial_inventory:
- 80.9
- 11.3
- 11.5
- 10.5
- 0.9
- 5.3
- 2.8
- 10.3
- 1.6
- 7.2
- 11.7
- 9.4
supply_injection:
  per_period:
  - node: 0
    amount: 7.79
weights:
  supply_reward_weight: 1.0
  cost_weight: 0.054
  risk_weight: 0.05
cvar:
  lambda: 0.0
  tau: 0.2
